### ISSUE TITLE
자바 컴파일러 버전 오류

### ISSUE THREAD

**Issue by ljh3491** [agemor/neis-api#13]
class file has wrong version 55.0, should be 52.0
라는 로그가 뜨는데 현 jdk 11버전에서 52에 해당하는 jdk 8fh 버전을 바꾸고 환경변수를 아무리 체크 해봐도 고쳐지지 않는데 혹시 jdk 11버전에서 쓸 수 있는 방법이 없나요? 또는 jdk 11에 대응하도록 재컴파일 해주실 수 없는지 질의 합니다. 감사합니다.

**Comment by agemor** [comment]
확인 결과 현재 컴파일된 버전이 JDK 11.0.1 입니다.

@ljh3491 님이 사용하시는 컴파일러 버전이 JDK 8 로 맞춰져 있어 저런 오류가 나오는 것으로 보입니다.
설정에서 JDK 버전을 11로 올리시거나, 여의치 않으시면 소스코드를 그대로 프로젝트에 포함하여 사용하시는 것을 추천드립니다!
