### ISSUE TITLE
알러지 정보도 활용했으면 합니다.

### ISSUE THREAD

**Issue by sys4cad** [agemor/neis-api#9]
String getAlergyText() 를 통해서 급식표 하단의 

"1.난류 2.우유 3.메밀 4.땅콩 5.대두 6.밀 7.고등어 8.게 9.새우 10.돼지고기 11.복숭아 12.토마토 13.아황산류 14.호두 15.닭고기16.쇠고기 17.오징어 18.조개류(굴,전복,홍합 포함)"

을 반환하였으면 합니다.

**Comment by Users2530** [comment]
나이스에서 교육청 주소를 바꿔가면서 봤더니 식단표 하단에 표시되는 알레르기 정보는 모두 같더군요. 
사견입니다만, 따로 함수를 만드는 것보다는 알레르기 표시를 복사해서 소스 코드에 직접 넣으시는 게 좋을 것 같습니다.
